### ISSUE TITLE
npm run build 好像有点问题，生成的页面显示不了，但npm run dev就可以正常访问。

### ISSUE THREAD

**Issue by yabusaio** [jm-team/ng-seed#1]

**Comment by ICELI** [comment]
`npm run build` 打包的生产环境代码需要web server，之前提供了[nginx](https://github.com/jm-team/ng-seed/blob/master/doc/nginx.conf)的基础配置参考。
最新的版本新增了直接基于express的Node 服务，现在你可以通过`npm run start` 查看build之后的页面   (配置读取的dev)    
`npm run dev` 开发环境因为用了webpack-dev-server,所以可以直接访问
